### ISSUE TITLE
Plugin doesn't work on Windows

### ISSUE THREAD

**Issue by jaichandra** [superwolff/metalsmith-in-place#44]
metalsmith-in-place plugin doesn't work in Windows. Below is the error I get. The same application builds fine on Mac.

I am using metalsmith-in-place and metalsmith-layouts plugins. Below is the code snippet from my build file:

```
.use(discoverHelpers({
        directory: paths.src + '/helpers',
        pattern: /\.js$/
      }))  
      .use(inPlace({
        engine: "handlebars",
        partials: paths.src + "/partials",
        pattern: "**/*.hbs",
        rename: true
      }))
      .use(layouts({
        engine: "handlebars",
        default: "index.hbs",
        directory: paths.src + "/layouts/",
        pattern: "**/*.html"
      }))
      .on('error', console.log.bind(console)) 
```

If I remove the inPlace (metalsmith-in-place), the error goes off even on windows. But, obviously the application doesn't work as the helpers are not compiled any more.

Error:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: The partial menu/nav could not be found
    at Object.invokePartial (Z:\sample\node_modules\handlebars\dist\cjs\handlebars\runtime.js:266:11)
    at Object.invokePartialWrapper [as invokePartial] (Z:\sample\node_modules\handlebars\dist\cjs\handlebars\ru
    at Object.eval (eval at createFunctionContext (Z:\sample\node_modules\handlebars\dist\cjs\handlebars\compil
    at main (Z:\sample\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (Z:\sample\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (Z:\sample\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at Z:\sample\node_modules\consolidate\lib\consolidate.js:734:16
    at Z:\sample\node_modules\consolidate\lib\consolidate.js:143:5
    at Promise._execute (Z:\sample\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (Z:\sample\node_modules\bluebird\js\release\promise.js:473:18)
    at new Promise (Z:\sample\node_modules\bluebird\js\release\promise.js:77:14)
    at promisify (Z:\sample\node_modules\consolidate\lib\consolidate.js:136:10)
    at exports.handlebars.render (Z:\sample\node_modules\consolidate\lib\consolidate.js:724:10)
    at convert (Z:\sample\node_modules\metalsmith-in-place\lib\index.js:123:7)
    at Z:\sample\node_modules\metalsmith-in-place\node_modules\async\lib\async.js:181:20
    at Object.async.forEachOf.async.eachOf (Z:\sample\node_modules\metalsmith-in-place\node_modules\async\lib\a

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\npm\\node_modules\\npm\\bin\\
npm ERR! node v4.4.3
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! sample@1.0.0 gulp: `gulp "build"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sample@1.0.0 gulp script 'gulp "build"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sample package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp "build"
npm ERR! You can get their info via:
npm ERR!     npm owner ls sample
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     Z:\sample\npm-debug.log
```

**Comment by jaichandra** [comment]
Here's the fix that worked. https://github.com/jaichandra/metalsmith-in-place/commit/7744439b360b96b4135fb6ecb2813d23c07861b4

**Comment by ismay** [comment]
Can you confirm if the latest release has solved this issue for you?

**Comment by doodzik** [comment]
I'm going to assume that this issue is fixed. We don't have the ability to reproduce it.
If it isn't please let us know.

**Comment by jaichandra** [comment]
Its working now. Thanks!

**Comment by doodzik** [comment]
Thank you for letting us know :)
