### ISSUE TITLE
fails if partials contain comments with block-partials

### ISSUE THREAD

**Issue by jaichandra** [superwolff/metalsmith-in-place#46]
if the partial contains comments like below:

```
<!--
{{!
/**
 * This is a component
 *
 * @param   {string}  content
 * @example
 * {{#> partial}}
 *     {{> another-partial}}
 * {{/ partial}}
 */
}}
 -->
```

the plugin fails with error:
```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Parse error on line 14:
...sight here..."}} * {{/ partial}}
----------------------^
Expecting 'EOF', got 'OPEN_ENDBLOCK'
    at Object.parseError (../node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:267:19)
    at Object.parse (../node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:336:30)
    at HandlebarsEnvironment.parse (../node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:43)
    at compileInput (../node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:514:19)
    at Object.ret (../node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:523:18)
    at Object.invokePartialWrapper [as invokePartial] (../node_modules/handlebars/dist/cjs/handlebars/runtime.js:72:46)
    at Object.eval (eval at createFunctionContext (../node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:28)
    at main (../node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (../node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (../node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at ../node_modules/consolidate/lib/consolidate.js:734:16
    at ../node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (../node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (../node_modules/bluebird/js/release/promise.js:473:18)
    at new Promise (../node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (../node_modules/consolidate/lib/consolidate.js:136:10)
```

**Comment by ismay** [comment]
Hmm, do you have the full file that's causing the error?

**Comment by jaichandra** [comment]
Here's the complete file:
```
<!-- Popover component start -->
<!--
{{!
/**
 * Base component to display popovers. This component can load html or another partial as content.
 * To load inline content, use component as block partial.
 * See example: comments.hbs
 *
 * @param   {string}  content   Path to a handlebars partial to load a content
 *
 * @example
 * {{#> common/popover}}
 *     {{>common/fe-textarea-vert rows="2" cols="60" label="" placeholder="Enter headline of insight here..."}}
 * {{/ common/popover}}
 */
}}
 -->
<div class="popover-container-wrapper hide">
  <div class="popover-container">
    <i class="sif sif-delete box-close-button"></i>
    {{#if content}}
      {{> (lookup . 'content')}}
    {{else}}
      {{> @partial-block }}
    {{/if}}
  </div>
</div>
<!-- Popover component end -->
```

**Comment by jaichandra** [comment]
ok... looks like the problem with not with block-partials in the comments. Its with the comment tag that we use. If I replace `{{! ... }}` with `{{!-- ... --}}`, it works. Not sure if this is an issue with this plugin or handlebars. But, I believe the comment tag without double dash (`{{! ... }}`) is a valid comment.

**Comment by ismay** [comment]
Hmm ok, well the handlebars is parsed by consolidate.js, maybe open an issue there to see what the intended behaviour is. Anyway, thanks for reporting!
